### PR TITLE
Added query params, added ua, cleaned ui and code

### PR DESCRIPTION
**Pull request by Ryfters**
### 1. Added optional query parameters: 
   - red=link will redirect to such link once clicked on
   - img=image link will show the image instead of the pixel 
### 2. Added UA:
   - Noticed that it wouldnt load images without another ua set to return the image, so it would bug
   - Added vercelbot ua
### 3. Cleaned code&UI:
   - Modified multiple code parts, such as using req.nextUrl.pathname instead of req.url.slice("/"). 
   - Modified the embed to send fields, instead of footer& description
### 4. Silenced Vercel & /favicon hits

### CODE REVIEW

**Comment by Ryfters** [comment]
i've changed smth from my version, so i'll check it
EDIT: i forgot the second " in "twitterbot/", should work now

**Comment by obfuscated-loop** [comment]
You pushed your Discord webhook...

**Comment by Ryfters** [comment]
> You pushed your Discord webhook...

Yh, realised it when I got spammed random memes after 2m, but I've deleted it

**Comment by Zaid-maker** [comment]
> > You pushed your Discord webhook...
> 
> Yh, realised it when I got spammed random memes after 2m, but I've deleted it

revert your change please

**Comment by lulu5239** [comment]
As it says in the `middleware.js` script ("Triggered view-logger **V2**"), this is more like an advanced version of this repository, possibly less understandable. The `page.html` says that only scripters should be able to log the IP address of whoever opened the view-logger in their browser.
*I agree that Vercel's requests to the website shouldn't trigger the view-logger.*

**Pull request closed without merging**
