### PR TITLE
Dont't leak Webhooks

### PR DESCRIPTION
**Pull request by Zaid-maker**
#2 people are stupid they leak webhooks

This PR simplifies the process of not leaking secrets like token or webhook url, and update the guide to tell put the URL during deplyment

@lulu5239 merge

### CODE REVIEW

**Comment by sk337** [comment]
the gitignore only ignores `.env*.local` and not regular .env files

**Comment by sk337** [comment]
and I recommend for clarity having the example content be `WEBHOOK_URL=` so the dumb skids don't spend 30 minutes figuring out the equal sign is required and that cant just paste it in

**Comment by Zaid-maker** [comment]
> and I recommend for clarity having the example content be `WEBHOOK_URL=` so the dumb skids don't spend 30 minutes figuring out the equal sign is required and that cant just paste it in

Ohh yeah!! on it

**Comment by tpglitch** [comment]
vercel is cooking rn :fire:

**Comment by tpglitch** [comment]
Maybe add dotenv for local?

**Comment by Zaid-maker** [comment]
> Maybe add dotenv for local?

No need i tested it works fine

**Comment by Zaid-maker** [comment]
> vercel is cooking rn 🔥

Yup due to NTTS

**Comment by lulu5239** [comment]
Changing the steps from what has been shown in the video can make it harder for people to understand.
Maybe it's because I'm on mobile, but I don't see an "Environment Variable" tab on GitHub. If you are referring to a Vercel feature, the step of cloning the repository still should be done before setting the webhook URL.

**Comment by Hacksore** [comment]
lil bro just merge this to stop **MOAR** people from leaking their webhooks

**Comment by Zaid-maker** [comment]
> Changing the steps from what has been shown in the video can make it harder for people to understand. Maybe it's because I'm on mobile, but I don't see an "Environment Variable" tab on GitHub. If you are referring to a Vercel feature, the step of cloning the repository still should be done before setting the webhook URL.

Yea the Environment variables is set from vercel when deploying.

Yea it will be hard but people are leaking webhooks so yeah they have to do it to make everyone safe.

Found a way to prompt user to put the URL as a secret while deploying the project.

**Comment by Zaid-maker** [comment]
You can update the Guide according to you ✨️

**Comment by Zaid-maker** [comment]
With new Deploy Button it is now Required to put the URL before Deploying

image

**Review by lulu5239 — APPROVED** [review]

**Review by lulu5239 — CHANGES_REQUESTED** [review]
Need to edit the steps (2 should only be about creating the webhook and copying its URL, 3 maybe should say that the cloning process now requires entering the webhook URL), and to update link at "this link".

**Comment by Zaid-maker** [comment]
Sure! I was waiting for your approval. Updating it right away

**Review by lulu5239 — APPROVED** [review]

**Comment by Zaid-maker** [comment]
❤️ 🎉

**Pull request merged**
